### ISSUE TITLE
Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by jiji87432** [liuwel/docker-mycat#1]
您好，请教个问题，我用的docker for mac，按照您给的步骤编译，运行，总是报错，提示Pool overlaps with other one on this address space（在这个地址空间与其他的池重叠）

**Comment by liuwel** [comment]
您好！感谢您的反馈
我用mac os x 测试了一下 除了build mysql容器的时候/etc/localtime报错 把这段注释掉 就可以了
没有出现您说的问题 麻烦确认下是不是重复启动服务导致的 
以下是我测试的环境信息
系统：
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

**Comment by liuwel** [comment]
@jiji87432   没什么问题的话 我就关闭了

**Comment by jiji87432** [comment]
好的，谢谢您的解答
