### ISSUE TITLE
mysql 8.0 docker 报错

### ISSUE THREAD

**Issue by Hkesd** [liuwel/docker-mycat#2]
修改了mysql、mycat版本，docker-compose 启动报错

只修改了Dockerfile，没有修改docker-compose.yml

错误信息：
m1       | 2020-05-06T10:00:43.337665Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.20) initializing of server in progress as process 43
m1       | 2020-05-06T10:00:43.338704Z 0 [ERROR] [MY-010187] [Server] Could not open file '/var/log/mysql/error.log' for error logging: No such file or directory
m1       | 2020-05-06T10:00:43.338813Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
m1       | 2020-05-06T10:00:43.338825Z 0 [ERROR] [MY-010119] [Server] Aborting
m1       | 2020-05-06T10:00:43.338876Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.20)  MySQL Community Server - GPL.

**Comment by liuwel** [comment]
mysql8 的  [Dockerfile](https://github.com/docker-library/mysql/tree/master/8.0) 里面引用了 config目录配置 在这里是不能直接继承的 可以在docker-compose.yml 里面直接使用 mysql8的image
不需要在本地build一个镜像了
我已经提交mysql8.0的整套配置 感兴趣的话可以拉下来跑一下 项目仅供学习参考
